# Generated by Django 4.2.6 on 2024-01-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model_DynamicTags_Username',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=55)),
                ('numero_conta_debito', models.CharField(max_length=7)),
                ('tags', models.CharField(max_length=155)),
                ('decription_rule', models.CharField(max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name='Model_RelacaoContas_Fornecedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=25)),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ModelContasGNRE_Estados_X_Contas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conta_uf', models.CharField(max_length=2)),
                ('conta_numero', models.IntegerField(default=0)),
                ('conta_debito', models.IntegerField()),
                ('modelo', models.CharField(max_length=25)),
            ],
        ),
    ]
