# Generated by Django 4.2.6 on 2023-10-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelContasGNRE_Estados_x_Contas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conta_uf', models.CharField(max_length=2)),
                ('conta_numero', models.IntegerField(default=0)),
            ],
        ),
    ]
