# Generated by Django 4.2.6 on 2024-01-10 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_payroll_relation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_ManualTags_Username',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=55)),
                ('numero_conta_credito', models.CharField(max_length=7)),
                ('numero_conta_debito', models.CharField(max_length=7)),
                ('tag', models.CharField(max_length=155)),
                ('decription_rule', models.CharField(max_length=125)),
            ],
        ),
    ]
