# Generated by Django 4.2.6 on 2023-10-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_payroll_relation', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelcontasgnre_estados_x_contas',
            name='conta_debito',
            field=models.IntegerField(default=1246),
            preserve_default=False,
        ),
    ]
