# Generated by Django 4.2.6 on 2024-01-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_payroll_relation', '0002_model_manualtags_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_manualtags_username',
            name='cnpj_cpf',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='model_manualtags_username',
            name='company',
            field=models.CharField(default='', max_length=125),
            preserve_default=False,
        ),
    ]
