# Generated by Django 4.2.6 on 2024-01-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_payroll_relation', '0003_model_manualtags_username_cnpj_cpf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_manualtags_username',
            name='id_company',
            field=models.CharField(default='', max_length=8),
            preserve_default=False,
        ),
    ]
