# Generated by Django 4.2.6 on 2023-10-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_payroll_relation', '0003_modelcontasgnre_estados_x_contas_conta_debito'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelContasGNRE_Estados_x_Contas_MODELO_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conta_uf', models.CharField(max_length=2)),
                ('conta_numero', models.IntegerField(default=0)),
                ('conta_debito', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ModelContasGNRE_Estados_x_Contas_MODELO_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conta_uf', models.CharField(max_length=2)),
                ('conta_numero', models.IntegerField(default=0)),
                ('conta_debito', models.IntegerField()),
            ],
        ),
    ]
