# Generated by Django 4.2.6 on 2023-11-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_payroll_relation', '0004_modelcontasgnre_estados_x_contas_modelo_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelcontasgnre_estados_x_contas',
            name='modelo',
            field=models.CharField(default='modelo_1', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelcontasgnre_estados_x_contas_modelo_2',
            name='modelo',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelcontasgnre_estados_x_contas_modelo_3',
            name='modelo',
            field=models.CharField(default='modelo_2', max_length=25),
            preserve_default=False,
        ),
    ]
