# Generated by Django 4.2.6 on 2024-01-12 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_payroll_relation', '0004_model_manualtags_username_id_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model_manualtags_username',
            name='id_company',
        ),
    ]
