# Generated by Django 4.2.6 on 2024-01-12 16:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_payroll_relation', '0005_remove_model_manualtags_username_id_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_manualtags_username',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 12, 13, 35, 54, 733724)),
        ),
        migrations.AddField(
            model_name='model_manualtags_username',
            name='update_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 12, 13, 35, 54, 733724)),
        ),
    ]
