# Generated by Django 4.2.6 on 2024-01-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_payroll_relation', '0005_modelcontasgnre_estados_x_contas_modelo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_RelacaoContasFornecedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=25)),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
    ]
