# Generated by Django 4.2.6 on 2024-01-12 16:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_payroll_relation', '0006_model_manualtags_username_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_manualtags_username',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 12, 13, 37, 48, 886903)),
        ),
        migrations.AlterField(
            model_name='model_manualtags_username',
            name='update_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 12, 13, 37, 48, 902481)),
        ),
    ]
