# Generated by Django 4.2.6 on 2024-01-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_payroll_relation', '0006_model_relacaocontasfornecedores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_ConfigTags_By_USER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=55)),
                ('activity_id', models.IntegerField()),
                ('tag', models.CharField(max_length=55)),
            ],
        ),
    ]
