# Generated by Django 4.2.6 on 2024-01-08 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_payroll_relation', '0007_model_configtags_by_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model_ConfigTags_By_USER',
            new_name='Model_Config_Tags_By_USER',
        ),
    ]
