# Generated by Django 4.2.6 on 2024-01-12 16:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_payroll_relation', '0007_alter_model_manualtags_username_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model_manualtags_username',
            name='cnpj_cpf',
        ),
        migrations.RemoveField(
            model_name='model_manualtags_username',
            name='company',
        ),
        migrations.RemoveField(
            model_name='model_manualtags_username',
            name='decription_rule',
        ),
        migrations.RemoveField(
            model_name='model_manualtags_username',
            name='numero_conta_credito',
        ),
        migrations.AddField(
            model_name='model_manualtags_username',
            name='id_company',
            field=models.CharField(default='', max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='model_manualtags_username',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 12, 13, 44, 40, 940467)),
        ),
        migrations.AlterField(
            model_name='model_manualtags_username',
            name='update_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 12, 13, 44, 40, 940467)),
        ),
    ]
