# Generated by Django 4.2.6 on 2024-01-15 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_payroll_relation', '0008_remove_model_manualtags_username_cnpj_cpf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_ConfigAccounts_Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_company', models.CharField(max_length=8)),
                ('code_account', models.CharField(max_length=8)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 1, 15, 13, 28, 33, 686059))),
                ('update_at', models.DateTimeField(default=datetime.datetime(2024, 1, 15, 13, 28, 33, 686059))),
            ],
        ),
        migrations.AlterField(
            model_name='model_manualtags_username',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 15, 13, 28, 33, 701683)),
        ),
        migrations.AlterField(
            model_name='model_manualtags_username',
            name='update_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 15, 13, 28, 33, 701683)),
        ),
    ]
