# Generated by Django 4.2.6 on 2024-01-22 12:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_payroll_relation', '0016_model_plano_contas_de_para_antigo_x_novo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_plano_contas_de_para_antigo_x_novo',
            name='company_code',
            field=models.CharField(default='', max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='model_configaccounts_client',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 22, 9, 10, 31, 482269)),
        ),
        migrations.AlterField(
            model_name='model_configaccounts_client',
            name='update_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 22, 9, 10, 31, 482269)),
        ),
        migrations.AlterField(
            model_name='model_manualtags_username',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 22, 9, 10, 31, 482269)),
        ),
        migrations.AlterField(
            model_name='model_manualtags_username',
            name='update_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 22, 9, 10, 31, 482269)),
        ),
        migrations.AlterField(
            model_name='model_plano_contas_antigo_x_novo',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 22, 9, 10, 31, 482269)),
        ),
        migrations.AlterField(
            model_name='model_plano_contas_antigo_x_novo',
            name='update_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 22, 9, 10, 31, 482269)),
        ),
        migrations.AlterField(
            model_name='model_plano_contas_de_para_antigo_x_novo',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 22, 9, 10, 31, 482269)),
        ),
        migrations.AlterField(
            model_name='model_plano_contas_de_para_antigo_x_novo',
            name='update_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 22, 9, 10, 31, 482269)),
        ),
    ]
