# Generated by Django 4.2.6 on 2024-02-02 16:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_payroll_relation', '0017_model_plano_contas_de_para_antigo_x_novo_company_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_plano_contas_de_para_antigo_x_novo',
            name='insert_JB',
            field=models.CharField(default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='model_plano_contas_de_para_antigo_x_novo',
            name='update_at_JB',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 2, 13, 38, 1, 500437)),
        ),
        migrations.AlterField(
            model_name='model_configaccounts_client',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 2, 13, 38, 1, 497438)),
        ),
        migrations.AlterField(
            model_name='model_configaccounts_client',
            name='update_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 2, 13, 38, 1, 497438)),
        ),
        migrations.AlterField(
            model_name='model_manualtags_username',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 2, 13, 38, 1, 498437)),
        ),
        migrations.AlterField(
            model_name='model_manualtags_username',
            name='update_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 2, 13, 38, 1, 498437)),
        ),
        migrations.AlterField(
            model_name='model_plano_contas_antigo_x_novo',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 2, 13, 38, 1, 499938)),
        ),
        migrations.AlterField(
            model_name='model_plano_contas_antigo_x_novo',
            name='update_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 2, 13, 38, 1, 499938)),
        ),
        migrations.AlterField(
            model_name='model_plano_contas_de_para_antigo_x_novo',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 2, 13, 38, 1, 500437)),
        ),
        migrations.AlterField(
            model_name='model_plano_contas_de_para_antigo_x_novo',
            name='update_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 2, 13, 38, 1, 500437)),
        ),
    ]
